name: Deploy AWS Lambda Function

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  FUNCTION_NAME: AwsLambdaDemo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore ./src/${{ env.FUNCTION_NAME }}.csproj

    - name: Build Project
      run: dotnet build ./src/${{ env.FUNCTION_NAME }}.csproj --configuration Release
      
    - name: Publish Lambda
      run:  dotnet lambda deploy-function AwsLambdaDemo \
            --region us-east-1 \
            --function-role arn:aws:iam::570829448606:role/Aws_Test_Profile_Role \
    - name: Post deploy status
      run: echo "Deployment complete!"
